;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	org-beginning-of-line
	org-return
	org-self-insert-command
	smex
	))

(setq mc/cmds-to-run-once
      '(
	keyboard-escape-quit
	kill-region
	org-end-of-line
	org-export-dispatch
	org-kill-line
	org-meta-return
	))
